server.port: 9090

spring:
  application.name: DataProcessor

streams:
  ai-analysis-start: ${STREAMS_AI_ANALYSIS_START_KEY}
  ai-analysis-dlq: ${STREAMS_AI_ANALYSIS_DLQ_KEY}
  group: ${STREAMS_GROUP}