server.port: 9090

spring:
  application.name: DataProcessor
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:config/ai.yml

streams:
  ai-analysis-start: ${STREAMS_AI_ANALYSIS_START_KEY}
  ai-analysis-dlq: ${STREAMS_AI_ANALYSIS_DLQ_KEY}
  group: ${STREAMS_GROUP}

logging:
  level:
    org.springframework.ai.retry: ERROR
